rootfs: Fix syntax error in xorg.conf selection initscript
Commit 0d9c896 "rootfs: Add support for using X with a mainline kernel"
replaced the static xorg.conf with a symlink created on bootup. But the
initscript setting the symlink had a syntax error which prevented X from
starting up with an l4t kernel. Fix it.

Change-Id: I11a17218c783c9e2e413f80746e84cd3b99ac99b
Signed-off-by: Nikolaus Schulz <nikolaus.schulz@avionic-design.de>
Reviewed-on: http://review.adnet.avionic-design.de/7870
Reviewed-by: Bert van Hall <bert.vanhall@avionic-design.de>

diff --git a/board/meerkat-l4t/rootfs_overlay/etc/init.d/S89xorg-l4t b/board/meerkat-l4t/rootfs_overlay/etc/init.d/S89xorg-l4t
--- a/board/meerkat-l4t/rootfs_overlay/etc/init.d/S89xorg-l4t
+++ b/board/meerkat-l4t/rootfs_overlay/etc/init.d/S89xorg-l4t
@@ -30,7 +30,7 @@ case "$1" in
 		[ ! -e "$xorg_conf" -o -L "$xorg_conf" ] || exit 0
 
 		echo -n "Selecting xorg.conf "
-		set_xorg_conf && echo "done." || { echo "FAILED." ; exit 1 }
+		set_xorg_conf && echo "done." || { echo "FAILED." ; exit 1 ; }
 		;;
 	*)
 		echo "usage: $0 {start|restart}"
